cameras/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = 'cameras'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('ad/', admin.site.urls),
    path('cameralist/', views.ClassroomListView.as_view(), name='cameralist'),
    path('<int:pk>/',views.DetailView.as_view(),name='detail'),
    path('<int:camera_id>/screenshot',views.screenshot,name='screenshot'),
    path('<int:camera_id>/player',views.player,name='player'),
]

classroom/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('cameras.urls')),
#    path('cameras/', include('cameras.urls')),
    path('admin/', admin.site.urls),
]

cameras/models.py
# -*- coding: utf-8 -*-
from django.db import models

# Create your models here.


class Camera(models.Model):
    classroom_text = models.CharField(max_length=128,verbose_name="教室")
    camera_ip_text = models.CharField(max_length=128,verbose_name="摄像头IP")
    people_number  = models.IntegerField(default=0)
    
    def __str__(self):
        return "<Classroom: {} IP: {}>".format(self.classroom_text,self.camera_ip_text)
            

cameras/views.py
import re
import time 
import io
import os

import mimetypes
from PIL import Image
import cv2
import numpy as np

from django.views import generic, View
from django.http import StreamingHttpResponse,HttpResponse
from django.shortcuts import render, get_object_or_404
from django.conf import settings
# Create your views here.

from .models import Camera
from .driver.loader import Loader
from .utils import tools
from .net.ssd_wrapper import SSD
config_file = "./cameras/net/configs/vgg_ssd512_coco_trainval35k.yaml"
dataset_type = "coco"
weight = "./cameras/net/model/vgg_ssd512_coco_trainval35k.pth"
score_threshold=0.15
ssd = SSD(config_file,dataset_type,weight,score_threshold)
# loader = Loader("/share/dong/class_test/03.mp4")
# img = loader.get_frame()
# print("test start predict")
# tmp = time.time()
# img = ssd.predict(img)
# print("test end predict")
# print(time.time()-tmp)
class IndexView(generic.ListView):
    template_name = 'cameras/index.html'
    context_object_name = "cameras_list"

    def get_queryset(self):
        return Camera.objects.all()

class ClassroomListView(generic.ListView):
    print("cameralist view")
    template_name = 'cameras/classroomlist.html'
    context_object_name = "cameras_list"

    def get_queryset(self):
        return Camera.objects.all()

class DetailView(generic.DetailView):
    model = Camera
    template_name = "cameras/detail.html"

def screenshot(request,camera_id):
    camera = get_object_or_404(Camera, pk=camera_id)
    loader = Loader(camera.camera_ip_text)
    img = loader.get_frame()
    if img is not None:
        print("img shape in screen shot:", img.shape)
    number = 0
    img = cv2.resize(img, (480, 270))  
    number, img = ssd.predict(img)
    camera.people_number = number
    camera.save()
    content = tools.img_to_str(img)
    return HttpResponse(content,content_type="image/png")

    
def player(request,camera_id):
    camera = get_object_or_404(Camera, pk=camera_id)
    loader = Loader(camera.camera_ip_text)
    # loader = TestLoader()
    return StreamingHttpResponse(gen(loader,camera), 
                                content_type="multipart/x-mixed-replace; boundary=frame")

def gen(loader,camera):
    while True:
        img = loader.get_frame() 
        number = 0
        if img is not None and settings.DEBUG:
            print("img shape in gen:", img.shape)
        img = cv2.resize(img, (640, 360))
        number, img = ssd.predict(img)
        camera.people_number = number
        camera.save()
        frame = tools.img_to_str(img)
        yield (
            b'--frame\r\n'
            b'Content-Type: image/png\r\n\r\n' + frame + b'\r\n\r\n'
        )

class TestLoader():
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.frames = [open(f+'.jpg','rb').read() for f in ['2','3','4']]

    def pop(self):
        time.sleep(1)
        return self.frames[int(time.time())%3]





    

cameras/templates/cameras/classroomlist.html
{% include 'cameras/head.html' %}
<nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
          <div class="navbar-header">
            <a class="navbar-brand" href="{% url 'cameras:index' %}">智能教室检测系统</a>
          </div>
          <div id="navbar" class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
              <li><a href="{% url 'cameras:index' %}">主页</a></li>
              <li class="active"><a href="{% url 'cameras:cameralist' %}">教室列表</a></li>
              <li><a href="../ad/">监控管理</a></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
</nav>

<div class="container block-center" style="margin-top:100px;">
  {% if cameras_list %}
    <div class="row">
    {% for camera in cameras_list %}

        {% if forloop.first %}
            <div class="col-md-1"><ul>
        {% endif %}
        <li><a href="{% url 'cameras:detail' camera.id %}" target="_self">{{ camera.classroom_text }}</a></li>
        {% if forloop.last %}
            </ul></div>
        {% endif %}
        {% if forloop.counter|divisibleby:2 %}
            {% if forloop.last != 1 %}
            </ul></div>
            <div class="col-md-1"><ul>
            {% endif %}
        {% endif %}
    {% endfor %}
    </div>
    {% else %}
        <p>No cameras are available.</p>
    {% endif %}
</div>

{% include 'cameras/foot.html' %}

cameras/templates/cameras/detail.html
{% include 'cameras/head.html' %}
<nav class="navbar navbar-inverse navbar-fixed-top">
                <div class="container">
                  <div class="navbar-header">
                    <a class="navbar-brand" href="{% url 'cameras:index' %}">智能教室检测系统</a>
                  </div>
                  <div id="navbar" class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                      <li><a href="{% url 'cameras:index' %}">主页</a></li>
                      <li><a href="{% url 'cameras:cameralist' %}">教室列表</a></li>
                      <li><a href="../ad/">监控管理</a></li>
                    </ul>
                  </div><!--/.nav-collapse -->
                </div>
</nav>

<div class="container block-center" style="margin-top:100px;">
        <div class="block-center">
                <img src="{% url 'cameras:player' camera.id %}">
        </div>
        <h3>教室: {{ camera.classroom_text }}</h3>
        <h3>摄像头IP: {{ camera.camera_ip_text }}</h3>
</div>

{% include 'cameras/foot.html' %}

cameras/templates/cameras/foot.html
{% load static %}
<footer class="footer" style="margin-top:50px;">
        <div class="container">
          <p class="text-center">&copy; DLUT 2019</p>
        </div>
</footer>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

cameras/templates/cameras/head.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <title>Bootstrap 实例</title>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1"> 
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  <!-- <script src="{% static 'js/bootstrap.min.js' %}"></script> -->
</head>
<body>

cameras/templates/cameras/index.html
{% include 'cameras/head.html' %}

<nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
          <div class="navbar-header">
            <a class="navbar-brand" href="{% url 'cameras:index' %}">智能教室检测系统</a>
          </div>
          <div id="navbar" class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
              <li class="active"><a href="{% url 'cameras:index' %}">主页</a></li>
              <li><a href="{% url 'cameras:cameralist' %}">教室列表</a></li>
              <li><a href="ad/">监控管理</a></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
</nav>

<!-- <div class="container block-center" style="margin-top:30px;margin-left:auto;margin-right:auto"> -->
<div class="container block-center" style="margin-top:100px; margin-left:auto; margin-right:auto">
    {% if cameras_list %}
        {% for camera in cameras_list %}
            {% if forloop.first %}
                <div class="row">
            {% endif %}
            <div class="col-md-4">
                <a class="text-center" target="_self" href="{% url 'cameras:detail' camera.id %}">
                    <img src="{% url 'cameras:screenshot' camera.id %}" class="img-responsive block-center" width="480" height="270">
                    <p class="text-center">{{ camera.classroom_text }}</p>
                </a>
            </div>
            {% if forloop.last %}
                </div>
            {% endif %}
            {% if forloop.counter|divisibleby:3 %}
                {% if forloop.last != 1 %}
                    </div>
                    <div class="row">
                    <div class="panel-heading">
                    <h3 class="panel-title"> </h3>
                    </div>
                    </div>
                    <div class="row">
                {% endif %}
            {% endif %}
            
            
        {% endfor %}
    {% else %}
        <p>No cameras are available.</p>
    {% endif %}
</div>

{% include 'cameras/foot.html' %}

cameras/templates/cameras/navbar.html
<div class="container">
        <h2>主页</h2>
        <ul class="nav nav-pills">
            <li class="nav-item">
                <a class="nav-link active" href="#">主页</a>
            </li>
            <li class="nav-item">
                    <a class="nav-link" href="#">教室列表</a>
            </li>
            <li class="nav-item">
                    <a class="nav-link" href="#">摄像头管理</a>
            </li>
            <li class="nav-item">
                    <a class="nav-link" href="#">About</a>
            </li>
        </ul>
</div>